name: Use API Key

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set API Key as an Environment Variable
        env:
          API_KEY: ${{ secrets.API_KEY }}

